WITH CTE AS (
    SELECT 
    TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAY_NAME,
    {{ day_type('STARTED_AT') }} as DAY_TYPE,
    {{ get_season('STARTED_AT') }} as STATION_OF_YEAR
    FROM {{ source('demo', 'bike') }}
    WHERE STARTED_AT <> 'started_at'

)

SELECT 
    *
FROM CTE




